apiVersion: v1
data:
  nginx.conf: |
    events {}
    http {
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$request_time" "$upstream_response_time"';
        access_log /var/log/nginx/access.log main;
        server {
            listen 80;
            location / {
                root /usr/share/nginx/html;
                index index.html index.htm;
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kata-cm
  namespace: kata-ns
