apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kata-app
  name: kata-app
  namespace: kata-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kata-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kata-app
    spec:
      serviceAccountName: logs-svc 
      containers:
        - image: nginx:latest
          name: nginx
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: kata-cm
