apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: log-reader
  namespace: kata-ns
rules:
  - apiGroups: [""] # Core API group
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
