apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kata-app
  name: app-deployment
  namespace: kata-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kata-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kata-app
    spec:
      containers:
      - image: nginx:latest
        name: kata-app
        ports:
          - containerPort: 80

