apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kata-app-service
  name: kata-app-service
  namespace: kata-ns
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: kata-app
  type: ClusterIP
